### ISSUE TITLE
OBS Websocket password config missing

### ISSUE THREAD

**Issue by kpcenti** [RCVolus/obs-google-sheet-importer#4]
It seems to not run when "Enable Authentication" is ticked on. I couldn't find a config file that lets me enter the password for OBS Websocket.

**Comment by kpcenti** [comment]
I would receive this error upon running start.bat with authentication on.

{
  error: 'Authentication Failed.',
  'message-id': '1',
  status: 'error',
  messageId: '1'
}

**Comment by sdomi4** [comment]
I have added a config for the address and password of OBS Websocket, it still defaults to localhost and no password, but allows configuration if needed.
