### ISSUE TITLE
Compatibility with OBS Versions >28?

### ISSUE THREAD

**Issue by OvrilPT** [RCVolus/obs-google-sheet-importer#8]
I migrated my OBS instance to OBS 29.0.2 and I'm getting "Error: Cannot find module 'obs-websocket-js'".

Since OBS Version 28, the WebSocket is included in the program, without the need for the plugin, is this the issue?

Thanks for the help.

**Comment by OvrilPT** [comment]
I'm sorry, I'm not very technical in this domain, what would npm install do in this case? And where should I run it? Inside this tool's directory?

**Comment by sdomi4** [comment]
The command installs the necessary dependencies to interact with OBS. The steps are described in the [Readme](https://github.com/RCVolus/obs-google-sheet-importer#installation) :)

**Comment by OvrilPT** [comment]
I have done so, sorry for not reading correctly the Readme.

Still, when running the tool, it only returns "pause" and doesn't go past that, never connecting with OBS.

Sorry for bothering with all this, I've used this tool in the past on an earlier version of OBS and I enjoyed it very much, just now having this issues trying to install it on a different computer with a newer version of OBS.

**Comment by Laraakaa** [comment]
Could you maybe share the full log / error message you get? It's gonna be especially interesting what is going to be returned before you mention the "pause", I'm almost certain there needs to be some other message or hint there.

**Comment by OvrilPT** [comment]
Hey, all I get is this in the terminal when I run "start.bat" (cut some of the path just for privacy):

```
F:\...\obs-google-sheet-importer-master>node index.js

F:\....\obs-google-sheet-importer-master>pause
Press any key to continue . . .
```

**Comment by sdomi4** [comment]
Turns out the websocket integrated to OBS changed everything about the way it communicates. The tool is now updated and should work. Note a few details have changed (hiding and showing text sources needs a `;` now). The readme is updated to reflect the changes.
